kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pv-claim
  labels:
    app: vprodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: default # to be EBS